# Generated by Django 4.1 on 2022-09-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='complete',
        ),
        migrations.AddField(
            model_name='cart',
            name='complet',
            field=models.BooleanField(default=False),
        ),
    ]
