# Generated by Django 4.1 on 2022-09-09 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_cart_complete_cart_complet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='complet',
            new_name='complete',
        ),
    ]
