# Generated by Django 4.1 on 2022-09-12 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_complet_cart_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendingproduct',
            old_name='products',
            new_name='product',
        ),
    ]
